import { describe, expect, test } from "bun:test";
import {
  createOrganizationLogoUrl,
  normalizeStoredOrganizationLogoUrl,
  ORGANIZATION_LOGO_KEY_PREFIX,
  OrganizationLogoUrlError,
} from "./organization-logo";

const LOGO_KEY = `${ORGANIZATION_LOGO_KEY_PREFIX}11111111-2222-3333-4444-555555555555`;

describe("organization logo URL policy", () => {
  test("creates and accepts generated local logo URLs outside production", () => {
    const url = createOrganizationLogoUrl(LOGO_KEY);

    expect(url).toBe(
      "http://127.0.0.1:8787/r2/logos/11111111-2222-3333-4444-555555555555"
    );
    expect(normalizeStoredOrganizationLogoUrl(url)).toBe(url);
  });

  test("accepts generated production CDN logo URLs", () => {
    const url =
      "https://cdn.kayle.id/logos/11111111-2222-3333-4444-555555555555";

    expect(normalizeStoredOrganizationLogoUrl(url)).toBe(url);
  });

  test("normalizes empty logo values to null", () => {
    expect(normalizeStoredOrganizationLogoUrl("")).toBeNull();
    expect(normalizeStoredOrganizationLogoUrl(null)).toBeNull();
    expect(normalizeStoredOrganizationLogoUrl(undefined)).toBeUndefined();
  });

  test("rejects external and non-generated logo URLs", () => {
    expect(() =>
      normalizeStoredOrganizationLogoUrl("https://example.com/logo.png")
    ).toThrow(OrganizationLogoUrlError);
    expect(() =>
      normalizeStoredOrganizationLogoUrl("data:image/svg+xml;base64,PHN2Zy8+")
    ).toThrow(OrganizationLogoUrlError);
    expect(() =>
      normalizeStoredOrganizationLogoUrl(
        "https://cdn.kayle.id/logos/11111111-2222-3333-4444-555555555555?x=1"
      )
    ).toThrow(OrganizationLogoUrlError);
  });

  test("rejects storage keys that were not generated by the logo uploader", () => {
    expect(() => createOrganizationLogoUrl("logos/manual.png")).toThrow(
      OrganizationLogoUrlError
    );
  });
});
