/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MarketingRouteImport } from './routes/_marketing'
import { Route as LegalRouteImport } from './routes/_legal'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as MarketingIndexRouteImport } from './routes/_marketing/index'
import { Route as LegalTermsRouteImport } from './routes/_legal/terms'
import { Route as LegalPrivacyRouteImport } from './routes/_legal/privacy'
import { Route as AuthVerify2faRouteImport } from './routes/_auth/verify-2fa'
import { Route as AuthVerifyRouteImport } from './routes/_auth/verify'
import { Route as AuthSignOutRouteImport } from './routes/_auth/sign-out'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppAccountRouteImport } from './routes/_app/account'
import { Route as MarketingDemoIndexRouteImport } from './routes/_marketing/demo.index'
import { Route as AppWebhooksIndexRouteImport } from './routes/_app/webhooks/index'
import { Route as AppOrganizationsIndexRouteImport } from './routes/_app/organizations/index'
import { Route as AppApiKeysIndexRouteImport } from './routes/_app/api-keys/index'
import { Route as AppAdminIndexRouteImport } from './routes/_app/admin/index'
import { Route as AppAccountIndexRouteImport } from './routes/_app/account/index'
import { Route as MarketingDemoIdRouteImport } from './routes/_marketing/demo.id'
import { Route as MarketingDemoAgeRouteImport } from './routes/_marketing/demo.age'
import { Route as AuthOrganizationsSelectRouteImport } from './routes/_auth/organizations/select'
import { Route as AuthOrganizationsCreateRouteImport } from './routes/_auth/organizations/create'
import { Route as AppWebhooksEndpointRouteImport } from './routes/_app/webhooks/$endpoint'
import { Route as AppOrganizationsSettingsRouteImport } from './routes/_app/organizations/settings'
import { Route as AppOrganizationsPublicRouteImport } from './routes/_app/organizations/public'
import { Route as AppOrganizationsMembersRouteImport } from './routes/_app/organizations/members'
import { Route as AppOrganizationsDomainsRouteImport } from './routes/_app/organizations/domains'
import { Route as AppOrganizationsBusinessRouteImport } from './routes/_app/organizations/business'
import { Route as AppOrganizationsAuditLogsRouteImport } from './routes/_app/organizations/audit-logs'
import { Route as AppApiKeysKeyRouteImport } from './routes/_app/api-keys/$key'
import { Route as AppAdminCostAnalyticsRouteImport } from './routes/_app/admin/cost-analytics'
import { Route as AppAccountSecurityRouteImport } from './routes/_app/account/security'
import { Route as ApiApiStartOrgVerificationRouteImport } from './routes/_api/api/start-org-verification'
import { Route as AppWebhooksEventsEventRouteImport } from './routes/_app/webhooks/events/$event'
import { Route as ApiApiWebhooksSplatRouteImport } from './routes/_api/api/webhooks/$'
import { Route as ApiApiInternalWebhookReceiverRouteImport } from './routes/_api/api/internal/webhook-receiver'
import { Route as ApiApiDemoSplatRouteImport } from './routes/_api/api/demo/$'
import { Route as ApiApiAuthSplatRouteImport } from './routes/_api/api/auth/$'
import { Route as ApiApiAnalyticsSplatRouteImport } from './routes/_api/api/analytics/$'
import { Route as ApiApiAdminSplatRouteImport } from './routes/_api/api/admin/$'

const MarketingRoute = MarketingRouteImport.update({
  id: '/_marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/_legal',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingRoute,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => LegalRoute,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LegalRoute,
} as any)
const AuthVerify2faRoute = AuthVerify2faRouteImport.update({
  id: '/verify-2fa',
  path: '/verify-2fa',
  getParentRoute: () => AuthRoute,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignOutRoute = AuthSignOutRouteImport.update({
  id: '/sign-out',
  path: '/sign-out',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const MarketingDemoIndexRoute = MarketingDemoIndexRouteImport.update({
  id: '/demo/',
  path: '/demo/',
  getParentRoute: () => MarketingRoute,
} as any)
const AppWebhooksIndexRoute = AppWebhooksIndexRouteImport.update({
  id: '/webhooks/',
  path: '/webhooks/',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizationsIndexRoute = AppOrganizationsIndexRouteImport.update({
  id: '/organizations/',
  path: '/organizations/',
  getParentRoute: () => AppRoute,
} as any)
const AppApiKeysIndexRoute = AppApiKeysIndexRouteImport.update({
  id: '/api-keys/',
  path: '/api-keys/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountIndexRoute = AppAccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAccountRoute,
} as any)
const MarketingDemoIdRoute = MarketingDemoIdRouteImport.update({
  id: '/demo/id',
  path: '/demo/id',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingDemoAgeRoute = MarketingDemoAgeRouteImport.update({
  id: '/demo/age',
  path: '/demo/age',
  getParentRoute: () => MarketingRoute,
} as any)
const AuthOrganizationsSelectRoute = AuthOrganizationsSelectRouteImport.update({
  id: '/organizations/select',
  path: '/organizations/select',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOrganizationsCreateRoute = AuthOrganizationsCreateRouteImport.update({
  id: '/organizations/create',
  path: '/organizations/create',
  getParentRoute: () => AuthRoute,
} as any)
const AppWebhooksEndpointRoute = AppWebhooksEndpointRouteImport.update({
  id: '/webhooks/$endpoint',
  path: '/webhooks/$endpoint',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizationsSettingsRoute =
  AppOrganizationsSettingsRouteImport.update({
    id: '/organizations/settings',
    path: '/organizations/settings',
    getParentRoute: () => AppRoute,
  } as any)
const AppOrganizationsPublicRoute = AppOrganizationsPublicRouteImport.update({
  id: '/organizations/public',
  path: '/organizations/public',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizationsMembersRoute = AppOrganizationsMembersRouteImport.update({
  id: '/organizations/members',
  path: '/organizations/members',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizationsDomainsRoute = AppOrganizationsDomainsRouteImport.update({
  id: '/organizations/domains',
  path: '/organizations/domains',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizationsBusinessRoute =
  AppOrganizationsBusinessRouteImport.update({
    id: '/organizations/business',
    path: '/organizations/business',
    getParentRoute: () => AppRoute,
  } as any)
const AppOrganizationsAuditLogsRoute =
  AppOrganizationsAuditLogsRouteImport.update({
    id: '/organizations/audit-logs',
    path: '/organizations/audit-logs',
    getParentRoute: () => AppRoute,
  } as any)
const AppApiKeysKeyRoute = AppApiKeysKeyRouteImport.update({
  id: '/api-keys/$key',
  path: '/api-keys/$key',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminCostAnalyticsRoute = AppAdminCostAnalyticsRouteImport.update({
  id: '/admin/cost-analytics',
  path: '/admin/cost-analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountSecurityRoute = AppAccountSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AppAccountRoute,
} as any)
const ApiApiStartOrgVerificationRoute =
  ApiApiStartOrgVerificationRouteImport.update({
    id: '/_api/api/start-org-verification',
    path: '/api/start-org-verification',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppWebhooksEventsEventRoute = AppWebhooksEventsEventRouteImport.update({
  id: '/webhooks/events/$event',
  path: '/webhooks/events/$event',
  getParentRoute: () => AppRoute,
} as any)
const ApiApiWebhooksSplatRoute = ApiApiWebhooksSplatRouteImport.update({
  id: '/_api/api/webhooks/$',
  path: '/api/webhooks/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiApiInternalWebhookReceiverRoute =
  ApiApiInternalWebhookReceiverRouteImport.update({
    id: '/_api/api/internal/webhook-receiver',
    path: '/api/internal/webhook-receiver',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiApiDemoSplatRoute = ApiApiDemoSplatRouteImport.update({
  id: '/_api/api/demo/$',
  path: '/api/demo/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiApiAuthSplatRoute = ApiApiAuthSplatRouteImport.update({
  id: '/_api/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiApiAnalyticsSplatRoute = ApiApiAnalyticsSplatRouteImport.update({
  id: '/_api/api/analytics/$',
  path: '/api/analytics/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiApiAdminSplatRoute = ApiApiAdminSplatRouteImport.update({
  id: '/_api/api/admin/$',
  path: '/api/admin/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MarketingIndexRoute
  '/account': typeof AppAccountRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-out': typeof AuthSignOutRoute
  '/verify': typeof AuthVerifyRoute
  '/verify-2fa': typeof AuthVerify2faRoute
  '/privacy': typeof LegalPrivacyRoute
  '/terms': typeof LegalTermsRoute
  '/api/start-org-verification': typeof ApiApiStartOrgVerificationRoute
  '/account/security': typeof AppAccountSecurityRoute
  '/admin/cost-analytics': typeof AppAdminCostAnalyticsRoute
  '/api-keys/$key': typeof AppApiKeysKeyRoute
  '/organizations/audit-logs': typeof AppOrganizationsAuditLogsRoute
  '/organizations/business': typeof AppOrganizationsBusinessRoute
  '/organizations/domains': typeof AppOrganizationsDomainsRoute
  '/organizations/members': typeof AppOrganizationsMembersRoute
  '/organizations/public': typeof AppOrganizationsPublicRoute
  '/organizations/settings': typeof AppOrganizationsSettingsRoute
  '/webhooks/$endpoint': typeof AppWebhooksEndpointRoute
  '/organizations/create': typeof AuthOrganizationsCreateRoute
  '/organizations/select': typeof AuthOrganizationsSelectRoute
  '/demo/age': typeof MarketingDemoAgeRoute
  '/demo/id': typeof MarketingDemoIdRoute
  '/account/': typeof AppAccountIndexRoute
  '/admin/': typeof AppAdminIndexRoute
  '/api-keys/': typeof AppApiKeysIndexRoute
  '/organizations/': typeof AppOrganizationsIndexRoute
  '/webhooks/': typeof AppWebhooksIndexRoute
  '/demo/': typeof MarketingDemoIndexRoute
  '/api/admin/$': typeof ApiApiAdminSplatRoute
  '/api/analytics/$': typeof ApiApiAnalyticsSplatRoute
  '/api/auth/$': typeof ApiApiAuthSplatRoute
  '/api/demo/$': typeof ApiApiDemoSplatRoute
  '/api/internal/webhook-receiver': typeof ApiApiInternalWebhookReceiverRoute
  '/api/webhooks/$': typeof ApiApiWebhooksSplatRoute
  '/webhooks/events/$event': typeof AppWebhooksEventsEventRoute
}
export interface FileRoutesByTo {
  '/': typeof MarketingIndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-out': typeof AuthSignOutRoute
  '/verify': typeof AuthVerifyRoute
  '/verify-2fa': typeof AuthVerify2faRoute
  '/privacy': typeof LegalPrivacyRoute
  '/terms': typeof LegalTermsRoute
  '/api/start-org-verification': typeof ApiApiStartOrgVerificationRoute
  '/account/security': typeof AppAccountSecurityRoute
  '/admin/cost-analytics': typeof AppAdminCostAnalyticsRoute
  '/api-keys/$key': typeof AppApiKeysKeyRoute
  '/organizations/audit-logs': typeof AppOrganizationsAuditLogsRoute
  '/organizations/business': typeof AppOrganizationsBusinessRoute
  '/organizations/domains': typeof AppOrganizationsDomainsRoute
  '/organizations/members': typeof AppOrganizationsMembersRoute
  '/organizations/public': typeof AppOrganizationsPublicRoute
  '/organizations/settings': typeof AppOrganizationsSettingsRoute
  '/webhooks/$endpoint': typeof AppWebhooksEndpointRoute
  '/organizations/create': typeof AuthOrganizationsCreateRoute
  '/organizations/select': typeof AuthOrganizationsSelectRoute
  '/demo/age': typeof MarketingDemoAgeRoute
  '/demo/id': typeof MarketingDemoIdRoute
  '/account': typeof AppAccountIndexRoute
  '/admin': typeof AppAdminIndexRoute
  '/api-keys': typeof AppApiKeysIndexRoute
  '/organizations': typeof AppOrganizationsIndexRoute
  '/webhooks': typeof AppWebhooksIndexRoute
  '/demo': typeof MarketingDemoIndexRoute
  '/api/admin/$': typeof ApiApiAdminSplatRoute
  '/api/analytics/$': typeof ApiApiAnalyticsSplatRoute
  '/api/auth/$': typeof ApiApiAuthSplatRoute
  '/api/demo/$': typeof ApiApiDemoSplatRoute
  '/api/internal/webhook-receiver': typeof ApiApiInternalWebhookReceiverRoute
  '/api/webhooks/$': typeof ApiApiWebhooksSplatRoute
  '/webhooks/events/$event': typeof AppWebhooksEventsEventRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_legal': typeof LegalRouteWithChildren
  '/_marketing': typeof MarketingRouteWithChildren
  '/_app/account': typeof AppAccountRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-out': typeof AuthSignOutRoute
  '/_auth/verify': typeof AuthVerifyRoute
  '/_auth/verify-2fa': typeof AuthVerify2faRoute
  '/_legal/privacy': typeof LegalPrivacyRoute
  '/_legal/terms': typeof LegalTermsRoute
  '/_marketing/': typeof MarketingIndexRoute
  '/_api/api/start-org-verification': typeof ApiApiStartOrgVerificationRoute
  '/_app/account/security': typeof AppAccountSecurityRoute
  '/_app/admin/cost-analytics': typeof AppAdminCostAnalyticsRoute
  '/_app/api-keys/$key': typeof AppApiKeysKeyRoute
  '/_app/organizations/audit-logs': typeof AppOrganizationsAuditLogsRoute
  '/_app/organizations/business': typeof AppOrganizationsBusinessRoute
  '/_app/organizations/domains': typeof AppOrganizationsDomainsRoute
  '/_app/organizations/members': typeof AppOrganizationsMembersRoute
  '/_app/organizations/public': typeof AppOrganizationsPublicRoute
  '/_app/organizations/settings': typeof AppOrganizationsSettingsRoute
  '/_app/webhooks/$endpoint': typeof AppWebhooksEndpointRoute
  '/_auth/organizations/create': typeof AuthOrganizationsCreateRoute
  '/_auth/organizations/select': typeof AuthOrganizationsSelectRoute
  '/_marketing/demo/age': typeof MarketingDemoAgeRoute
  '/_marketing/demo/id': typeof MarketingDemoIdRoute
  '/_app/account/': typeof AppAccountIndexRoute
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_app/api-keys/': typeof AppApiKeysIndexRoute
  '/_app/organizations/': typeof AppOrganizationsIndexRoute
  '/_app/webhooks/': typeof AppWebhooksIndexRoute
  '/_marketing/demo/': typeof MarketingDemoIndexRoute
  '/_api/api/admin/$': typeof ApiApiAdminSplatRoute
  '/_api/api/analytics/$': typeof ApiApiAnalyticsSplatRoute
  '/_api/api/auth/$': typeof ApiApiAuthSplatRoute
  '/_api/api/demo/$': typeof ApiApiDemoSplatRoute
  '/_api/api/internal/webhook-receiver': typeof ApiApiInternalWebhookReceiverRoute
  '/_api/api/webhooks/$': typeof ApiApiWebhooksSplatRoute
  '/_app/webhooks/events/$event': typeof AppWebhooksEventsEventRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/dashboard'
    | '/sign-in'
    | '/sign-out'
    | '/verify'
    | '/verify-2fa'
    | '/privacy'
    | '/terms'
    | '/api/start-org-verification'
    | '/account/security'
    | '/admin/cost-analytics'
    | '/api-keys/$key'
    | '/organizations/audit-logs'
    | '/organizations/business'
    | '/organizations/domains'
    | '/organizations/members'
    | '/organizations/public'
    | '/organizations/settings'
    | '/webhooks/$endpoint'
    | '/organizations/create'
    | '/organizations/select'
    | '/demo/age'
    | '/demo/id'
    | '/account/'
    | '/admin/'
    | '/api-keys/'
    | '/organizations/'
    | '/webhooks/'
    | '/demo/'
    | '/api/admin/$'
    | '/api/analytics/$'
    | '/api/auth/$'
    | '/api/demo/$'
    | '/api/internal/webhook-receiver'
    | '/api/webhooks/$'
    | '/webhooks/events/$event'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/sign-in'
    | '/sign-out'
    | '/verify'
    | '/verify-2fa'
    | '/privacy'
    | '/terms'
    | '/api/start-org-verification'
    | '/account/security'
    | '/admin/cost-analytics'
    | '/api-keys/$key'
    | '/organizations/audit-logs'
    | '/organizations/business'
    | '/organizations/domains'
    | '/organizations/members'
    | '/organizations/public'
    | '/organizations/settings'
    | '/webhooks/$endpoint'
    | '/organizations/create'
    | '/organizations/select'
    | '/demo/age'
    | '/demo/id'
    | '/account'
    | '/admin'
    | '/api-keys'
    | '/organizations'
    | '/webhooks'
    | '/demo'
    | '/api/admin/$'
    | '/api/analytics/$'
    | '/api/auth/$'
    | '/api/demo/$'
    | '/api/internal/webhook-receiver'
    | '/api/webhooks/$'
    | '/webhooks/events/$event'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_legal'
    | '/_marketing'
    | '/_app/account'
    | '/_app/dashboard'
    | '/_auth/sign-in'
    | '/_auth/sign-out'
    | '/_auth/verify'
    | '/_auth/verify-2fa'
    | '/_legal/privacy'
    | '/_legal/terms'
    | '/_marketing/'
    | '/_api/api/start-org-verification'
    | '/_app/account/security'
    | '/_app/admin/cost-analytics'
    | '/_app/api-keys/$key'
    | '/_app/organizations/audit-logs'
    | '/_app/organizations/business'
    | '/_app/organizations/domains'
    | '/_app/organizations/members'
    | '/_app/organizations/public'
    | '/_app/organizations/settings'
    | '/_app/webhooks/$endpoint'
    | '/_auth/organizations/create'
    | '/_auth/organizations/select'
    | '/_marketing/demo/age'
    | '/_marketing/demo/id'
    | '/_app/account/'
    | '/_app/admin/'
    | '/_app/api-keys/'
    | '/_app/organizations/'
    | '/_app/webhooks/'
    | '/_marketing/demo/'
    | '/_api/api/admin/$'
    | '/_api/api/analytics/$'
    | '/_api/api/auth/$'
    | '/_api/api/demo/$'
    | '/_api/api/internal/webhook-receiver'
    | '/_api/api/webhooks/$'
    | '/_app/webhooks/events/$event'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  LegalRoute: typeof LegalRouteWithChildren
  MarketingRoute: typeof MarketingRouteWithChildren
  ApiApiStartOrgVerificationRoute: typeof ApiApiStartOrgVerificationRoute
  ApiApiAdminSplatRoute: typeof ApiApiAdminSplatRoute
  ApiApiAnalyticsSplatRoute: typeof ApiApiAnalyticsSplatRoute
  ApiApiAuthSplatRoute: typeof ApiApiAuthSplatRoute
  ApiApiDemoSplatRoute: typeof ApiApiDemoSplatRoute
  ApiApiInternalWebhookReceiverRoute: typeof ApiApiInternalWebhookReceiverRoute
  ApiApiWebhooksSplatRoute: typeof ApiApiWebhooksSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_marketing': {
      id: '/_marketing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_legal': {
      id: '/_legal'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/': {
      id: '/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_legal/terms': {
      id: '/_legal/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof LegalRoute
    }
    '/_legal/privacy': {
      id: '/_legal/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof LegalRoute
    }
    '/_auth/verify-2fa': {
      id: '/_auth/verify-2fa'
      path: '/verify-2fa'
      fullPath: '/verify-2fa'
      preLoaderRoute: typeof AuthVerify2faRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/verify': {
      id: '/_auth/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-out': {
      id: '/_auth/sign-out'
      path: '/sign-out'
      fullPath: '/sign-out'
      preLoaderRoute: typeof AuthSignOutRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account': {
      id: '/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/_marketing/demo/': {
      id: '/_marketing/demo/'
      path: '/demo'
      fullPath: '/demo/'
      preLoaderRoute: typeof MarketingDemoIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_app/webhooks/': {
      id: '/_app/webhooks/'
      path: '/webhooks'
      fullPath: '/webhooks/'
      preLoaderRoute: typeof AppWebhooksIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/organizations/': {
      id: '/_app/organizations/'
      path: '/organizations'
      fullPath: '/organizations/'
      preLoaderRoute: typeof AppOrganizationsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/api-keys/': {
      id: '/_app/api-keys/'
      path: '/api-keys'
      fullPath: '/api-keys/'
      preLoaderRoute: typeof AppApiKeysIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account/': {
      id: '/_app/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AppAccountIndexRouteImport
      parentRoute: typeof AppAccountRoute
    }
    '/_marketing/demo/id': {
      id: '/_marketing/demo/id'
      path: '/demo/id'
      fullPath: '/demo/id'
      preLoaderRoute: typeof MarketingDemoIdRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/demo/age': {
      id: '/_marketing/demo/age'
      path: '/demo/age'
      fullPath: '/demo/age'
      preLoaderRoute: typeof MarketingDemoAgeRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_auth/organizations/select': {
      id: '/_auth/organizations/select'
      path: '/organizations/select'
      fullPath: '/organizations/select'
      preLoaderRoute: typeof AuthOrganizationsSelectRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/organizations/create': {
      id: '/_auth/organizations/create'
      path: '/organizations/create'
      fullPath: '/organizations/create'
      preLoaderRoute: typeof AuthOrganizationsCreateRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/webhooks/$endpoint': {
      id: '/_app/webhooks/$endpoint'
      path: '/webhooks/$endpoint'
      fullPath: '/webhooks/$endpoint'
      preLoaderRoute: typeof AppWebhooksEndpointRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/organizations/settings': {
      id: '/_app/organizations/settings'
      path: '/organizations/settings'
      fullPath: '/organizations/settings'
      preLoaderRoute: typeof AppOrganizationsSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/organizations/public': {
      id: '/_app/organizations/public'
      path: '/organizations/public'
      fullPath: '/organizations/public'
      preLoaderRoute: typeof AppOrganizationsPublicRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/organizations/members': {
      id: '/_app/organizations/members'
      path: '/organizations/members'
      fullPath: '/organizations/members'
      preLoaderRoute: typeof AppOrganizationsMembersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/organizations/domains': {
      id: '/_app/organizations/domains'
      path: '/organizations/domains'
      fullPath: '/organizations/domains'
      preLoaderRoute: typeof AppOrganizationsDomainsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/organizations/business': {
      id: '/_app/organizations/business'
      path: '/organizations/business'
      fullPath: '/organizations/business'
      preLoaderRoute: typeof AppOrganizationsBusinessRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/organizations/audit-logs': {
      id: '/_app/organizations/audit-logs'
      path: '/organizations/audit-logs'
      fullPath: '/organizations/audit-logs'
      preLoaderRoute: typeof AppOrganizationsAuditLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/api-keys/$key': {
      id: '/_app/api-keys/$key'
      path: '/api-keys/$key'
      fullPath: '/api-keys/$key'
      preLoaderRoute: typeof AppApiKeysKeyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/cost-analytics': {
      id: '/_app/admin/cost-analytics'
      path: '/admin/cost-analytics'
      fullPath: '/admin/cost-analytics'
      preLoaderRoute: typeof AppAdminCostAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account/security': {
      id: '/_app/account/security'
      path: '/security'
      fullPath: '/account/security'
      preLoaderRoute: typeof AppAccountSecurityRouteImport
      parentRoute: typeof AppAccountRoute
    }
    '/_api/api/start-org-verification': {
      id: '/_api/api/start-org-verification'
      path: '/api/start-org-verification'
      fullPath: '/api/start-org-verification'
      preLoaderRoute: typeof ApiApiStartOrgVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/webhooks/events/$event': {
      id: '/_app/webhooks/events/$event'
      path: '/webhooks/events/$event'
      fullPath: '/webhooks/events/$event'
      preLoaderRoute: typeof AppWebhooksEventsEventRouteImport
      parentRoute: typeof AppRoute
    }
    '/_api/api/webhooks/$': {
      id: '/_api/api/webhooks/$'
      path: '/api/webhooks/$'
      fullPath: '/api/webhooks/$'
      preLoaderRoute: typeof ApiApiWebhooksSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_api/api/internal/webhook-receiver': {
      id: '/_api/api/internal/webhook-receiver'
      path: '/api/internal/webhook-receiver'
      fullPath: '/api/internal/webhook-receiver'
      preLoaderRoute: typeof ApiApiInternalWebhookReceiverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_api/api/demo/$': {
      id: '/_api/api/demo/$'
      path: '/api/demo/$'
      fullPath: '/api/demo/$'
      preLoaderRoute: typeof ApiApiDemoSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_api/api/auth/$': {
      id: '/_api/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_api/api/analytics/$': {
      id: '/_api/api/analytics/$'
      path: '/api/analytics/$'
      fullPath: '/api/analytics/$'
      preLoaderRoute: typeof ApiApiAnalyticsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_api/api/admin/$': {
      id: '/_api/api/admin/$'
      path: '/api/admin/$'
      fullPath: '/api/admin/$'
      preLoaderRoute: typeof ApiApiAdminSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppAccountRouteChildren {
  AppAccountSecurityRoute: typeof AppAccountSecurityRoute
  AppAccountIndexRoute: typeof AppAccountIndexRoute
}

const AppAccountRouteChildren: AppAccountRouteChildren = {
  AppAccountSecurityRoute: AppAccountSecurityRoute,
  AppAccountIndexRoute: AppAccountIndexRoute,
}

const AppAccountRouteWithChildren = AppAccountRoute._addFileChildren(
  AppAccountRouteChildren,
)

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppAdminCostAnalyticsRoute: typeof AppAdminCostAnalyticsRoute
  AppApiKeysKeyRoute: typeof AppApiKeysKeyRoute
  AppOrganizationsAuditLogsRoute: typeof AppOrganizationsAuditLogsRoute
  AppOrganizationsBusinessRoute: typeof AppOrganizationsBusinessRoute
  AppOrganizationsDomainsRoute: typeof AppOrganizationsDomainsRoute
  AppOrganizationsMembersRoute: typeof AppOrganizationsMembersRoute
  AppOrganizationsPublicRoute: typeof AppOrganizationsPublicRoute
  AppOrganizationsSettingsRoute: typeof AppOrganizationsSettingsRoute
  AppWebhooksEndpointRoute: typeof AppWebhooksEndpointRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
  AppApiKeysIndexRoute: typeof AppApiKeysIndexRoute
  AppOrganizationsIndexRoute: typeof AppOrganizationsIndexRoute
  AppWebhooksIndexRoute: typeof AppWebhooksIndexRoute
  AppWebhooksEventsEventRoute: typeof AppWebhooksEventsEventRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppAdminCostAnalyticsRoute: AppAdminCostAnalyticsRoute,
  AppApiKeysKeyRoute: AppApiKeysKeyRoute,
  AppOrganizationsAuditLogsRoute: AppOrganizationsAuditLogsRoute,
  AppOrganizationsBusinessRoute: AppOrganizationsBusinessRoute,
  AppOrganizationsDomainsRoute: AppOrganizationsDomainsRoute,
  AppOrganizationsMembersRoute: AppOrganizationsMembersRoute,
  AppOrganizationsPublicRoute: AppOrganizationsPublicRoute,
  AppOrganizationsSettingsRoute: AppOrganizationsSettingsRoute,
  AppWebhooksEndpointRoute: AppWebhooksEndpointRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
  AppApiKeysIndexRoute: AppApiKeysIndexRoute,
  AppOrganizationsIndexRoute: AppOrganizationsIndexRoute,
  AppWebhooksIndexRoute: AppWebhooksIndexRoute,
  AppWebhooksEventsEventRoute: AppWebhooksEventsEventRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignOutRoute: typeof AuthSignOutRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
  AuthVerify2faRoute: typeof AuthVerify2faRoute
  AuthOrganizationsCreateRoute: typeof AuthOrganizationsCreateRoute
  AuthOrganizationsSelectRoute: typeof AuthOrganizationsSelectRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthSignOutRoute: AuthSignOutRoute,
  AuthVerifyRoute: AuthVerifyRoute,
  AuthVerify2faRoute: AuthVerify2faRoute,
  AuthOrganizationsCreateRoute: AuthOrganizationsCreateRoute,
  AuthOrganizationsSelectRoute: AuthOrganizationsSelectRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface LegalRouteChildren {
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
}

const LegalRouteChildren: LegalRouteChildren = {
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
}

const LegalRouteWithChildren = LegalRoute._addFileChildren(LegalRouteChildren)

interface MarketingRouteChildren {
  MarketingIndexRoute: typeof MarketingIndexRoute
  MarketingDemoAgeRoute: typeof MarketingDemoAgeRoute
  MarketingDemoIdRoute: typeof MarketingDemoIdRoute
  MarketingDemoIndexRoute: typeof MarketingDemoIndexRoute
}

const MarketingRouteChildren: MarketingRouteChildren = {
  MarketingIndexRoute: MarketingIndexRoute,
  MarketingDemoAgeRoute: MarketingDemoAgeRoute,
  MarketingDemoIdRoute: MarketingDemoIdRoute,
  MarketingDemoIndexRoute: MarketingDemoIndexRoute,
}

const MarketingRouteWithChildren = MarketingRoute._addFileChildren(
  MarketingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  LegalRoute: LegalRouteWithChildren,
  MarketingRoute: MarketingRouteWithChildren,
  ApiApiStartOrgVerificationRoute: ApiApiStartOrgVerificationRoute,
  ApiApiAdminSplatRoute: ApiApiAdminSplatRoute,
  ApiApiAnalyticsSplatRoute: ApiApiAnalyticsSplatRoute,
  ApiApiAuthSplatRoute: ApiApiAuthSplatRoute,
  ApiApiDemoSplatRoute: ApiApiDemoSplatRoute,
  ApiApiInternalWebhookReceiverRoute: ApiApiInternalWebhookReceiverRoute,
  ApiApiWebhooksSplatRoute: ApiApiWebhooksSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
