/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MarketingRouteImport } from './routes/_marketing'
import { Route as LegalRouteImport } from './routes/_legal'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as MarketingIndexRouteImport } from './routes/_marketing/index'
import { Route as MarketingDemoRouteImport } from './routes/_marketing/demo'
import { Route as LegalTermsRouteImport } from './routes/_legal/terms'
import { Route as LegalPrivacyRouteImport } from './routes/_legal/privacy'
import { Route as AuthVerifyRouteImport } from './routes/_auth/verify'
import { Route as AuthSignOutRouteImport } from './routes/_auth/sign-out'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppAccountRouteImport } from './routes/_app/account'
import { Route as AppWebhooksIndexRouteImport } from './routes/_app/webhooks/index'
import { Route as AppApiKeysIndexRouteImport } from './routes/_app/api-keys/index'
import { Route as AppAccountIndexRouteImport } from './routes/_app/account/index'
import { Route as AuthOrganizationsSelectRouteImport } from './routes/_auth/organizations/select'
import { Route as AuthOrganizationsCreateRouteImport } from './routes/_auth/organizations/create'
import { Route as AppWebhooksEndpointRouteImport } from './routes/_app/webhooks/$endpoint'
import { Route as AppApiKeysKeyRouteImport } from './routes/_app/api-keys/$key'
import { Route as AppAccountSecurityRouteImport } from './routes/_app/account/security'
import { Route as AuthOrganizationsActiveSettingsRouteImport } from './routes/_auth/organizations/_active/settings'
import { Route as AuthOrganizationsActiveMembersRouteImport } from './routes/_auth/organizations/_active/members'
import { Route as AppWebhooksEventsEventRouteImport } from './routes/_app/webhooks/events/$event'
import { Route as ApiApiWebhooksSplatRouteImport } from './routes/_api/api/webhooks/$'
import { Route as ApiApiDemoSplatRouteImport } from './routes/_api/api/demo/$'
import { Route as ApiApiAuthSplatRouteImport } from './routes/_api/api/auth/$'
import { Route as ApiApiAnalyticsSplatRouteImport } from './routes/_api/api/analytics/$'

const MarketingRoute = MarketingRouteImport.update({
  id: '/_marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/_legal',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingDemoRoute = MarketingDemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => MarketingRoute,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => LegalRoute,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LegalRoute,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignOutRoute = AuthSignOutRouteImport.update({
  id: '/sign-out',
  path: '/sign-out',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AppWebhooksIndexRoute = AppWebhooksIndexRouteImport.update({
  id: '/webhooks/',
  path: '/webhooks/',
  getParentRoute: () => AppRoute,
} as any)
const AppApiKeysIndexRoute = AppApiKeysIndexRouteImport.update({
  id: '/api-keys/',
  path: '/api-keys/',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountIndexRoute = AppAccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAccountRoute,
} as any)
const AuthOrganizationsSelectRoute = AuthOrganizationsSelectRouteImport.update({
  id: '/organizations/select',
  path: '/organizations/select',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOrganizationsCreateRoute = AuthOrganizationsCreateRouteImport.update({
  id: '/organizations/create',
  path: '/organizations/create',
  getParentRoute: () => AuthRoute,
} as any)
const AppWebhooksEndpointRoute = AppWebhooksEndpointRouteImport.update({
  id: '/webhooks/$endpoint',
  path: '/webhooks/$endpoint',
  getParentRoute: () => AppRoute,
} as any)
const AppApiKeysKeyRoute = AppApiKeysKeyRouteImport.update({
  id: '/api-keys/$key',
  path: '/api-keys/$key',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountSecurityRoute = AppAccountSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AppAccountRoute,
} as any)
const AuthOrganizationsActiveSettingsRoute =
  AuthOrganizationsActiveSettingsRouteImport.update({
    id: '/organizations/_active/settings',
    path: '/organizations/settings',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthOrganizationsActiveMembersRoute =
  AuthOrganizationsActiveMembersRouteImport.update({
    id: '/organizations/_active/members',
    path: '/organizations/members',
    getParentRoute: () => AuthRoute,
  } as any)
const AppWebhooksEventsEventRoute = AppWebhooksEventsEventRouteImport.update({
  id: '/webhooks/events/$event',
  path: '/webhooks/events/$event',
  getParentRoute: () => AppRoute,
} as any)
const ApiApiWebhooksSplatRoute = ApiApiWebhooksSplatRouteImport.update({
  id: '/_api/api/webhooks/$',
  path: '/api/webhooks/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiApiDemoSplatRoute = ApiApiDemoSplatRouteImport.update({
  id: '/_api/api/demo/$',
  path: '/api/demo/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiApiAuthSplatRoute = ApiApiAuthSplatRouteImport.update({
  id: '/_api/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiApiAnalyticsSplatRoute = ApiApiAnalyticsSplatRouteImport.update({
  id: '/_api/api/analytics/$',
  path: '/api/analytics/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MarketingIndexRoute
  '/account': typeof AppAccountRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-out': typeof AuthSignOutRoute
  '/verify': typeof AuthVerifyRoute
  '/privacy': typeof LegalPrivacyRoute
  '/terms': typeof LegalTermsRoute
  '/demo': typeof MarketingDemoRoute
  '/account/security': typeof AppAccountSecurityRoute
  '/api-keys/$key': typeof AppApiKeysKeyRoute
  '/webhooks/$endpoint': typeof AppWebhooksEndpointRoute
  '/organizations/create': typeof AuthOrganizationsCreateRoute
  '/organizations/select': typeof AuthOrganizationsSelectRoute
  '/account/': typeof AppAccountIndexRoute
  '/api-keys/': typeof AppApiKeysIndexRoute
  '/webhooks/': typeof AppWebhooksIndexRoute
  '/api/analytics/$': typeof ApiApiAnalyticsSplatRoute
  '/api/auth/$': typeof ApiApiAuthSplatRoute
  '/api/demo/$': typeof ApiApiDemoSplatRoute
  '/api/webhooks/$': typeof ApiApiWebhooksSplatRoute
  '/webhooks/events/$event': typeof AppWebhooksEventsEventRoute
  '/organizations/members': typeof AuthOrganizationsActiveMembersRoute
  '/organizations/settings': typeof AuthOrganizationsActiveSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof MarketingIndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-out': typeof AuthSignOutRoute
  '/verify': typeof AuthVerifyRoute
  '/privacy': typeof LegalPrivacyRoute
  '/terms': typeof LegalTermsRoute
  '/demo': typeof MarketingDemoRoute
  '/account/security': typeof AppAccountSecurityRoute
  '/api-keys/$key': typeof AppApiKeysKeyRoute
  '/webhooks/$endpoint': typeof AppWebhooksEndpointRoute
  '/organizations/create': typeof AuthOrganizationsCreateRoute
  '/organizations/select': typeof AuthOrganizationsSelectRoute
  '/account': typeof AppAccountIndexRoute
  '/api-keys': typeof AppApiKeysIndexRoute
  '/webhooks': typeof AppWebhooksIndexRoute
  '/api/analytics/$': typeof ApiApiAnalyticsSplatRoute
  '/api/auth/$': typeof ApiApiAuthSplatRoute
  '/api/demo/$': typeof ApiApiDemoSplatRoute
  '/api/webhooks/$': typeof ApiApiWebhooksSplatRoute
  '/webhooks/events/$event': typeof AppWebhooksEventsEventRoute
  '/organizations/members': typeof AuthOrganizationsActiveMembersRoute
  '/organizations/settings': typeof AuthOrganizationsActiveSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_legal': typeof LegalRouteWithChildren
  '/_marketing': typeof MarketingRouteWithChildren
  '/_app/account': typeof AppAccountRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-out': typeof AuthSignOutRoute
  '/_auth/verify': typeof AuthVerifyRoute
  '/_legal/privacy': typeof LegalPrivacyRoute
  '/_legal/terms': typeof LegalTermsRoute
  '/_marketing/demo': typeof MarketingDemoRoute
  '/_marketing/': typeof MarketingIndexRoute
  '/_app/account/security': typeof AppAccountSecurityRoute
  '/_app/api-keys/$key': typeof AppApiKeysKeyRoute
  '/_app/webhooks/$endpoint': typeof AppWebhooksEndpointRoute
  '/_auth/organizations/create': typeof AuthOrganizationsCreateRoute
  '/_auth/organizations/select': typeof AuthOrganizationsSelectRoute
  '/_app/account/': typeof AppAccountIndexRoute
  '/_app/api-keys/': typeof AppApiKeysIndexRoute
  '/_app/webhooks/': typeof AppWebhooksIndexRoute
  '/_api/api/analytics/$': typeof ApiApiAnalyticsSplatRoute
  '/_api/api/auth/$': typeof ApiApiAuthSplatRoute
  '/_api/api/demo/$': typeof ApiApiDemoSplatRoute
  '/_api/api/webhooks/$': typeof ApiApiWebhooksSplatRoute
  '/_app/webhooks/events/$event': typeof AppWebhooksEventsEventRoute
  '/_auth/organizations/_active/members': typeof AuthOrganizationsActiveMembersRoute
  '/_auth/organizations/_active/settings': typeof AuthOrganizationsActiveSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/dashboard'
    | '/sign-in'
    | '/sign-out'
    | '/verify'
    | '/privacy'
    | '/terms'
    | '/demo'
    | '/account/security'
    | '/api-keys/$key'
    | '/webhooks/$endpoint'
    | '/organizations/create'
    | '/organizations/select'
    | '/account/'
    | '/api-keys/'
    | '/webhooks/'
    | '/api/analytics/$'
    | '/api/auth/$'
    | '/api/demo/$'
    | '/api/webhooks/$'
    | '/webhooks/events/$event'
    | '/organizations/members'
    | '/organizations/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/sign-in'
    | '/sign-out'
    | '/verify'
    | '/privacy'
    | '/terms'
    | '/demo'
    | '/account/security'
    | '/api-keys/$key'
    | '/webhooks/$endpoint'
    | '/organizations/create'
    | '/organizations/select'
    | '/account'
    | '/api-keys'
    | '/webhooks'
    | '/api/analytics/$'
    | '/api/auth/$'
    | '/api/demo/$'
    | '/api/webhooks/$'
    | '/webhooks/events/$event'
    | '/organizations/members'
    | '/organizations/settings'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_legal'
    | '/_marketing'
    | '/_app/account'
    | '/_app/dashboard'
    | '/_auth/sign-in'
    | '/_auth/sign-out'
    | '/_auth/verify'
    | '/_legal/privacy'
    | '/_legal/terms'
    | '/_marketing/demo'
    | '/_marketing/'
    | '/_app/account/security'
    | '/_app/api-keys/$key'
    | '/_app/webhooks/$endpoint'
    | '/_auth/organizations/create'
    | '/_auth/organizations/select'
    | '/_app/account/'
    | '/_app/api-keys/'
    | '/_app/webhooks/'
    | '/_api/api/analytics/$'
    | '/_api/api/auth/$'
    | '/_api/api/demo/$'
    | '/_api/api/webhooks/$'
    | '/_app/webhooks/events/$event'
    | '/_auth/organizations/_active/members'
    | '/_auth/organizations/_active/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  LegalRoute: typeof LegalRouteWithChildren
  MarketingRoute: typeof MarketingRouteWithChildren
  ApiApiAnalyticsSplatRoute: typeof ApiApiAnalyticsSplatRoute
  ApiApiAuthSplatRoute: typeof ApiApiAuthSplatRoute
  ApiApiDemoSplatRoute: typeof ApiApiDemoSplatRoute
  ApiApiWebhooksSplatRoute: typeof ApiApiWebhooksSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_marketing': {
      id: '/_marketing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_legal': {
      id: '/_legal'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/': {
      id: '/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/demo': {
      id: '/_marketing/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof MarketingDemoRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_legal/terms': {
      id: '/_legal/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof LegalRoute
    }
    '/_legal/privacy': {
      id: '/_legal/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof LegalRoute
    }
    '/_auth/verify': {
      id: '/_auth/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-out': {
      id: '/_auth/sign-out'
      path: '/sign-out'
      fullPath: '/sign-out'
      preLoaderRoute: typeof AuthSignOutRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account': {
      id: '/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/webhooks/': {
      id: '/_app/webhooks/'
      path: '/webhooks'
      fullPath: '/webhooks/'
      preLoaderRoute: typeof AppWebhooksIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/api-keys/': {
      id: '/_app/api-keys/'
      path: '/api-keys'
      fullPath: '/api-keys/'
      preLoaderRoute: typeof AppApiKeysIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account/': {
      id: '/_app/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AppAccountIndexRouteImport
      parentRoute: typeof AppAccountRoute
    }
    '/_auth/organizations/select': {
      id: '/_auth/organizations/select'
      path: '/organizations/select'
      fullPath: '/organizations/select'
      preLoaderRoute: typeof AuthOrganizationsSelectRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/organizations/create': {
      id: '/_auth/organizations/create'
      path: '/organizations/create'
      fullPath: '/organizations/create'
      preLoaderRoute: typeof AuthOrganizationsCreateRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/webhooks/$endpoint': {
      id: '/_app/webhooks/$endpoint'
      path: '/webhooks/$endpoint'
      fullPath: '/webhooks/$endpoint'
      preLoaderRoute: typeof AppWebhooksEndpointRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/api-keys/$key': {
      id: '/_app/api-keys/$key'
      path: '/api-keys/$key'
      fullPath: '/api-keys/$key'
      preLoaderRoute: typeof AppApiKeysKeyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account/security': {
      id: '/_app/account/security'
      path: '/security'
      fullPath: '/account/security'
      preLoaderRoute: typeof AppAccountSecurityRouteImport
      parentRoute: typeof AppAccountRoute
    }
    '/_auth/organizations/_active/settings': {
      id: '/_auth/organizations/_active/settings'
      path: '/organizations/settings'
      fullPath: '/organizations/settings'
      preLoaderRoute: typeof AuthOrganizationsActiveSettingsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/organizations/_active/members': {
      id: '/_auth/organizations/_active/members'
      path: '/organizations/members'
      fullPath: '/organizations/members'
      preLoaderRoute: typeof AuthOrganizationsActiveMembersRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/webhooks/events/$event': {
      id: '/_app/webhooks/events/$event'
      path: '/webhooks/events/$event'
      fullPath: '/webhooks/events/$event'
      preLoaderRoute: typeof AppWebhooksEventsEventRouteImport
      parentRoute: typeof AppRoute
    }
    '/_api/api/webhooks/$': {
      id: '/_api/api/webhooks/$'
      path: '/api/webhooks/$'
      fullPath: '/api/webhooks/$'
      preLoaderRoute: typeof ApiApiWebhooksSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_api/api/demo/$': {
      id: '/_api/api/demo/$'
      path: '/api/demo/$'
      fullPath: '/api/demo/$'
      preLoaderRoute: typeof ApiApiDemoSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_api/api/auth/$': {
      id: '/_api/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_api/api/analytics/$': {
      id: '/_api/api/analytics/$'
      path: '/api/analytics/$'
      fullPath: '/api/analytics/$'
      preLoaderRoute: typeof ApiApiAnalyticsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppAccountRouteChildren {
  AppAccountSecurityRoute: typeof AppAccountSecurityRoute
  AppAccountIndexRoute: typeof AppAccountIndexRoute
}

const AppAccountRouteChildren: AppAccountRouteChildren = {
  AppAccountSecurityRoute: AppAccountSecurityRoute,
  AppAccountIndexRoute: AppAccountIndexRoute,
}

const AppAccountRouteWithChildren = AppAccountRoute._addFileChildren(
  AppAccountRouteChildren,
)

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppApiKeysKeyRoute: typeof AppApiKeysKeyRoute
  AppWebhooksEndpointRoute: typeof AppWebhooksEndpointRoute
  AppApiKeysIndexRoute: typeof AppApiKeysIndexRoute
  AppWebhooksIndexRoute: typeof AppWebhooksIndexRoute
  AppWebhooksEventsEventRoute: typeof AppWebhooksEventsEventRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppApiKeysKeyRoute: AppApiKeysKeyRoute,
  AppWebhooksEndpointRoute: AppWebhooksEndpointRoute,
  AppApiKeysIndexRoute: AppApiKeysIndexRoute,
  AppWebhooksIndexRoute: AppWebhooksIndexRoute,
  AppWebhooksEventsEventRoute: AppWebhooksEventsEventRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignOutRoute: typeof AuthSignOutRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
  AuthOrganizationsCreateRoute: typeof AuthOrganizationsCreateRoute
  AuthOrganizationsSelectRoute: typeof AuthOrganizationsSelectRoute
  AuthOrganizationsActiveMembersRoute: typeof AuthOrganizationsActiveMembersRoute
  AuthOrganizationsActiveSettingsRoute: typeof AuthOrganizationsActiveSettingsRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthSignOutRoute: AuthSignOutRoute,
  AuthVerifyRoute: AuthVerifyRoute,
  AuthOrganizationsCreateRoute: AuthOrganizationsCreateRoute,
  AuthOrganizationsSelectRoute: AuthOrganizationsSelectRoute,
  AuthOrganizationsActiveMembersRoute: AuthOrganizationsActiveMembersRoute,
  AuthOrganizationsActiveSettingsRoute: AuthOrganizationsActiveSettingsRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface LegalRouteChildren {
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
}

const LegalRouteChildren: LegalRouteChildren = {
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
}

const LegalRouteWithChildren = LegalRoute._addFileChildren(LegalRouteChildren)

interface MarketingRouteChildren {
  MarketingDemoRoute: typeof MarketingDemoRoute
  MarketingIndexRoute: typeof MarketingIndexRoute
}

const MarketingRouteChildren: MarketingRouteChildren = {
  MarketingDemoRoute: MarketingDemoRoute,
  MarketingIndexRoute: MarketingIndexRoute,
}

const MarketingRouteWithChildren = MarketingRoute._addFileChildren(
  MarketingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  LegalRoute: LegalRouteWithChildren,
  MarketingRoute: MarketingRouteWithChildren,
  ApiApiAnalyticsSplatRoute: ApiApiAnalyticsSplatRoute,
  ApiApiAuthSplatRoute: ApiApiAuthSplatRoute,
  ApiApiDemoSplatRoute: ApiApiDemoSplatRoute,
  ApiApiWebhooksSplatRoute: ApiApiWebhooksSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
