/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplatRouteImport } from './routes/$'
import { Route as V1SplatRouteImport } from './routes/v1/$'
import { Route as PrivacySessionIdRouteImport } from './routes/privacy.$sessionId'

const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const V1SplatRoute = V1SplatRouteImport.update({
  id: '/v1/$',
  path: '/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacySessionIdRoute = PrivacySessionIdRouteImport.update({
  id: '/privacy/$sessionId',
  path: '/privacy/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/$': typeof SplatRoute
  '/privacy/$sessionId': typeof PrivacySessionIdRoute
  '/v1/$': typeof V1SplatRoute
}
export interface FileRoutesByTo {
  '/$': typeof SplatRoute
  '/privacy/$sessionId': typeof PrivacySessionIdRoute
  '/v1/$': typeof V1SplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$': typeof SplatRoute
  '/privacy/$sessionId': typeof PrivacySessionIdRoute
  '/v1/$': typeof V1SplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/$' | '/privacy/$sessionId' | '/v1/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/$' | '/privacy/$sessionId' | '/v1/$'
  id: '__root__' | '/$' | '/privacy/$sessionId' | '/v1/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SplatRoute: typeof SplatRoute
  PrivacySessionIdRoute: typeof PrivacySessionIdRoute
  V1SplatRoute: typeof V1SplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/$': {
      id: '/v1/$'
      path: '/v1/$'
      fullPath: '/v1/$'
      preLoaderRoute: typeof V1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy/$sessionId': {
      id: '/privacy/$sessionId'
      path: '/privacy/$sessionId'
      fullPath: '/privacy/$sessionId'
      preLoaderRoute: typeof PrivacySessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  SplatRoute: SplatRoute,
  PrivacySessionIdRoute: PrivacySessionIdRoute,
  V1SplatRoute: V1SplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
