/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BiometricLivenessRouteImport } from './routes/biometric/liveness'
import { Route as BiometricFullPipelineRouteImport } from './routes/biometric/full-pipeline'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BiometricLivenessRoute = BiometricLivenessRouteImport.update({
  id: '/biometric/liveness',
  path: '/biometric/liveness',
  getParentRoute: () => rootRouteImport,
} as any)
const BiometricFullPipelineRoute = BiometricFullPipelineRouteImport.update({
  id: '/biometric/full-pipeline',
  path: '/biometric/full-pipeline',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/biometric/full-pipeline': typeof BiometricFullPipelineRoute
  '/biometric/liveness': typeof BiometricLivenessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/biometric/full-pipeline': typeof BiometricFullPipelineRoute
  '/biometric/liveness': typeof BiometricLivenessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/biometric/full-pipeline': typeof BiometricFullPipelineRoute
  '/biometric/liveness': typeof BiometricLivenessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/biometric/full-pipeline'
    | '/biometric/liveness'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/biometric/full-pipeline'
    | '/biometric/liveness'
  id:
    | '__root__'
    | '/'
    | '/biometric/full-pipeline'
    | '/biometric/liveness'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BiometricFullPipelineRoute: typeof BiometricFullPipelineRoute
  BiometricLivenessRoute: typeof BiometricLivenessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biometric/liveness': {
      id: '/biometric/liveness'
      path: '/biometric/liveness'
      fullPath: '/biometric/liveness'
      preLoaderRoute: typeof BiometricLivenessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biometric/full-pipeline': {
      id: '/biometric/full-pipeline'
      path: '/biometric/full-pipeline'
      fullPath: '/biometric/full-pipeline'
      preLoaderRoute: typeof BiometricFullPipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BiometricFullPipelineRoute: BiometricFullPipelineRoute,
  BiometricLivenessRoute: BiometricLivenessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
