import { randomBytes } from "node:crypto";
import { existsSync } from "node:fs";
import { writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const SCRIPT_DIR = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(SCRIPT_DIR, "..");
const ENV_PATH = path.join(REPO_ROOT, ".env");

const SECRET_BYTES = 32;

const generateSecret = (): string => randomBytes(SECRET_BYTES).toString("hex");

const buildEnv =
  (): string => `# Generated by \`bun run env:setup\`. The script refuses to overwrite this file —
# delete it first if you want a fresh bootstrap.
#
# Maintainers should run \`bun run env:pull\` to replace this with the real dev
# secrets from Infisical.

# Database — matches infra/postgres/compose.yml.
NODE_ENV=development
DATABASE_URL=postgres://postgres:postgres@localhost:6432/kayle-id

# Redis — matches infra/redis/compose.yml. The Upstash REST shim runs on
# port 8079 with a pinned token so every contributor hits the same URL.
REDIS_URL=http://localhost:8079
REDIS_TOKEN=a-super-secret-token

# Random secrets — generated locally, no third-party account required.
AUTH_SECRET=${generateSecret()}
KAYLE_INTERNAL_TOKEN=${generateSecret()}
BIOMETRIC_VERIFIER_SECRET=${generateSecret()}
ORG_VERIFICATION_PEPPER=${generateSecret()}

# Public auth URL — the platform app proxies auth through localhost:3000.
PUBLIC_AUTH_URL=https://localhost:3000

# Public verify URL — used by the API when building verification_url in
# session responses. Points at the local verify worker dev server.
PUBLIC_VERIFY_URL=http://localhost:2999

# Email — the dev API logs the magic OTP and email body instead of calling
# Resend, so the from-address is only used to populate Better Auth payloads.
EMAIL_FROM_ADDRESS="Kayle ID <auth@kayle.id>"

# Dummy third-party credentials — the dev API logs the magic OTP and email
# body instead of calling Google or Resend, so these can stay as dummies
# unless you want to exercise the real OAuth or email flows.
GOOGLE_CLIENT_ID=dummy-google-client-id
GOOGLE_CLIENT_SECRET=dummy-google-client-secret
`;

const main = async (): Promise<void> => {
  const relativeEnvPath = path.relative(REPO_ROOT, ENV_PATH);

  if (existsSync(ENV_PATH)) {
    process.stdout.write(
      `Skipped ${relativeEnvPath} (already exists). Delete it and re-run for a fresh bootstrap.\n`
    );
    return;
  }

  await writeFile(ENV_PATH, buildEnv(), { mode: 0o600 });

  process.stdout.write(
    [
      `Created ${relativeEnvPath}.`,
      "Random hex was used for AUTH_SECRET, KAYLE_INTERNAL_TOKEN, BIOMETRIC_VERIFIER_SECRET, and ORG_VERIFICATION_PEPPER.",
      "REDIS_URL/REDIS_TOKEN point at the local Upstash REST shim (infra/redis/compose.yml).",
      "Google and Resend credentials are dummies — the dev API logs the magic OTP and email body instead of calling those services.",
      "",
      "Next steps:",
      "  bun run db:start       # bring up local Postgres",
      "  bun run redis:start    # bring up local Redis + Upstash shim",
      "  bun run db:setup       # apply migrations",
      "  bun run dev            # start every service",
      "",
    ].join("\n")
  );
};

await main();
