name: kayle-id-redis

services:
  redis:
    image: redis:7
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - kayle-id-redis-data:/data

  srh:
    image: hiett/serverless-redis-http:latest
    environment:
      SRH_MODE: env
      SRH_TOKEN: a-super-secret-token
      SRH_CONNECTION_STRING: redis://redis:6379
    ports:
      - "8079:80"
    depends_on:
      - redis

volumes:
  kayle-id-redis-data:
