name: Validate

on:
  push:
    branches:
      - main
      - staging
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd

      - name: Set up Bun workspace
        uses: ./.github/actions/setup-bun
        with:
          apt-packages: ripgrep

      - name: Run repository linting
        run: bun run lint
